import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Dil extends Translations {
  // ignore: prefer_const_constructors
  static final varsayilan = Locale("en", "US");
  // ignore: prefer_const_constructors
  static final diller = [Locale("tr", "TR"), Locale("en", "US")];

  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'giris': 'Login',
          'egitim': 'Training Attendance System',
          'ad-soyad': 'Name-Surname',
          'sicil': 'Registration Number',
          'egitimci-giris': 'Trainer Login',
          'sicil-no-alani-doldurun': 'Fill in the registration number field.',
          'sifre': 'Password',
          'ogrenci-giris': 'Trainee Login',
          'ders-seciniz': 'Select Training',
          'veriler-yükleniyor': 'Loading Data...',
          'cikis': 'Do you want to exit the application?',
          'hayir': 'No',
          'evet': 'Yes',
          'back': 'Do you want to return to the previous page?',
          'katilimcilar': 'Participants',
          'arama-yap': 'Search...',
          'icin-qr-kod': ' For QR Code',
          'hata': 'An error occurred: ',
          'yoklamaya-katildiniz': 'You participated in the roll call.',
          'scan-code': 'Scan QR Code',
          'admin-password': 'Admin Password',
          'sifre-hata': 'Wrong Password',
          'egitimci': 'Trainer',
          'katilimci': 'Participant',
          'ders': 'Training',
          'onay': 'I approve',
          'sicil-mevcut':
              'Would you like to update such a registry existing name?',
          'güncelle': 'Update',
          'iptal': 'Cancel',
          'hatali-giris': 'Incorrect Entry',
          'bilgileri-onayliyor-musunuz': 'Do you confirm information?',
          'katilimci-ekle': 'Add Participants',
          'ekle-guncelle': 'Add/Update',
          'geri-don': 'Back',
          'katilimci-sil': 'Delete Participant',
          'sil': 'Delete',
          'silinecek-kullanici': 'User to be Deleted: ',
          'boyle-sicil-yok': 'There is no such registration number.',
          'egitimci-ekle': 'Add Trainer',
          'ad-soyad:': 'Name Surname: ',
          'sicil:': 'Registration Number: ',
          'sifre:': 'Password: ',
          'sicil-mevcut-ismi-ve-sifre-gunc':
              'Would you like to update such a registry existing name and password?',
          'egitimci-sil': 'Delete Trainer',
          'egitim-ad': 'Training Name',
          'boyle-ders-yok': 'There is no such training.',
          'ekle': 'Add',
          'eklenecek-kullanici': 'User to be added: ',
          'boyle-egitim-var': 'Such training already exists.',
          'wifi-yok': 'No Internet connection',
          'wifi-kontrol': 'Please check your internet connection.',
          'wifi-ayar': 'WiFi Settings',
          'devam-et': 'Continue',
          'uygulama-kapat': 'Close Application',
        },
        'tr_TR': {
          'giris': 'Giriş',
          'egitim': 'Eğitim Yoklama Sistemi',
          'ad-soyad': 'Ad-Soyad',
          'sicil': 'Sicil Numarası',
          'egitimci-giris': 'Eğitimci Girişi',
          'sicil-no-alani-doldurun': 'Sicil numarası alanını doldurun.',
          'sifre': 'Şifre',
          'ogrenci-giris': 'Kursiyer Girişi',
          'ders-seciniz': 'Eğitim Seçiniz',
          'veriler-yükleniyor': 'Veriler yükleniyor...',
          'cikis': 'Uygulamadan çıkmak istiyor musunuz?',
          'evet': 'Evet',
          'hayir': 'Hayır',
          'back': 'Bir önceki sayfaya dönmek istiyor musunuz?',
          'katilimcilar': 'Katılımcılar',
          'arama-yap': 'Arama Yapın...',
          'icin-qr-kod': ' İçin QR Kod',
          'hata': 'Hata oluştu: ',
          'yoklamaya-katildiniz': 'Yoklamaya katıldınız.',
          'scan-code': 'QR Kodu Tarayın',
          'admin-password': 'Admin Şifre',
          'sifre-hata': 'Şifre Yanlış',
          'egitimci': 'Eğitimci',
          'katilimci': 'Katılımcı',
          'ders': 'Eğitim',
          'onay': 'Onaylıyorum',
          'sicil-mevcut':
              'Böyle bir sicil mevcut ismi güncellemek ister misin?',
          'güncelle': 'Güncelle',
          'iptal': 'İptal',
          'hatali-giris': 'Hatalı Giriş',
          'bilgileri-onayliyor-musunuz': 'Bilgileri onaylıyor musunuz?',
          'katilimci-ekle': 'Katılımcı Ekle',
          'ekle-guncelle': 'Ekle/Güncelle',
          'geri-don': 'Geri Dön',
          'katilimci-sil': 'Katılımcı Sil',
          'sil': 'Sil',
          'silinecek-kullanici': 'Silinecek Kullanıcı: ',
          'boyle-sicil-yok': 'Böyle bir sicil numarası yok.',
          'egitimci-ekle': 'Eğitimci Ekle',
          'ad-soyad:': 'Ad Soyad: ',
          'sicil:': 'Sicil Numarası: ',
          'sifre:': 'Şifre: ',
          'sicil-mevcut-ismi-ve-sifre-gunc':
              'Böyle bir sicil mevcut ismi ve şifreyi güncellemek ister misin?',
          'egitimci-sil': 'Eğitimci Sil',
          'egitim-ad': 'Eğitim Adı',
          'boyle-ders-yok': 'Böyle bir eğitim yok.',
          'ekle': 'Ekle',
          'eklenecek-kullanici': 'Eklenecek Kullanıcı: ',
          'boyle-egitim-var': 'Böyle bir eğitim zaten var.',
          'wifi-yok': 'İnternet Bağlantısı Yok',
          'wifi-kontrol': 'Lütfen internet bağlantınızı kontrol edin.',
          'wifi-ayar': 'WiFi Ayarları',
          'devam-et': 'Devam Et',
          'uygulama-kapat': 'Uygulamayı Kapat',
        }
      };
}
